services:
  openheart-protocol:
    restart: always
    build:
      context: .
    environment:
      DB_DSN: "${DB_DSN}"
#    network_mode: host
    networks:
      - internal
    ports:
      - "4444:4444"
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${DB_NAME}"
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./_data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - internal

networks:
  internal:
    name: internal
    external: false