services:
  openheart-protocol:
    restart: always
    build:
      context: .
    environment:
      DB_DSN: "changeUserName:changeMePassword!@tcp(db:3306)/changeDbName"
#    network_mode: host
    networks:
      - internal
    ports:
      - "4444:4444"
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "changeMeRoot!"
      MARIADB_DATABASE: "changeDbName"
      MARIADB_USER: "changeUserName"
      MARIADB_PASSWORD: "changeMePassword!"
    volumes:
      - ./_data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - internal

networks:
  internal:
    name: internal
    external: false